title: "Demo of Kener"
siteName: ""
home: "/"
logo: "/logo.png"
siteURL: "https://kener.ing"
favicon: "/logo96.png"
github:
    owner: "n3op2"
    repo: "status-page"
    incidentSince: 720
metaTags:
    description: "Kener: Open-source modern looking Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking service outages and improves how we communicate during incidents. And the best part? Kener integrates seamlessly with GitHub, making incident management a team effort—making it easier for us to track and fix issues together in a collaborative and friendly environment."
    keywords: "Node.js status page, Incident management tool, Service monitoring, Service outage tracking, Real-time status updates, GitHub integration for incidents, Open-source status page, Node.js monitoring application, Service reliability, User-friendly incident management, Collaborative incident resolution, Seamless outage communication, Service disruption tracker, Real-time incident alerts, Node.js status reporting"
    og:description: "Kener: Open-source Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking service outages and improves how we communicate during incidents. And the best part? Kener integrates seamlessly with GitHub, making incident management a team effort—making it easier for us to track and fix issues together in a collaborative and friendly environment."
    og:image: "https://kener.ing/ss.png"
    og:title: "Kener - Open-Source and Modern looking Node.js Status Page for Effortless Incident Management"
    og:type: "website"
    og:site_name: "Kener"
    twitter:card: "summary_large_image"
    twitter:site: "@_rajnandan_"
    twitter:creator: "@_rajnandan_"
    twitter:image: "https://kener.ing/ss.png"
    twitter:title: "Kener: Open-Source and Modern looking Node.js Status Page for Effortless Incident Management"
    twitter:description: "Kener: Open-source Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking service outages and improves how we communicate during incidents. And the best part? Kener integrates seamlessly with GitHub, making incident management a team effort—making it easier for us to track and fix issues together in a collaborative and friendly environment."
nav:
    - name: "SEQUENCE"
      url: "/sequence/url"
    - name: "VERITABLE"
      url: "https://google.com/veritable"
    - name: "Github"
      url: "https://github.com/n3op2/status-page"
hero:
    title: Digital Catapult 
    subtitle: Where inovation thrives 
footerHTML: |
    <a href="https://github.com/digicatapult target="_blank" rel="noreferrer" class="font-medium underline underline-offset-4">
      Digitalcatapult.com
    </a>
i18n:
    defaultLocale: "en"
    locales:
        en: "English"
        hi: "हिन्दी"
        zh-CN: "中文"
        ja: "日本語"
        vi: "Tiếng Việt"
pattern: "squares"
analytics:
  - id: "G-Q3MLRXCBFT"
    type: "GA"

